{% set version = "2.5.7" %}

package:
  name: wslink
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wslink/wslink-{{ version }}.tar.gz
  sha256: ed14c2b4749ea231a105a23334d2e0c7783204b2033f46104972a189ea235818

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp <4
    - msgpack-python >=1,<2

test:
  imports:
    - wslink
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/kitware/wslink
  summary: Python/JavaScript library for communicating over WebSocket
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - kwrobot
