{% set name = "wslink" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wslink-{{ version }}.tar.gz
  sha256: 4d72e6fc76c5798b2069445103041c2f095869dc9d541ee6e7a52ff42d34d6e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp <4

test:
  imports:
    - wslink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kitware/wslink
  summary: Python/JavaScript library for communicating over WebSocket
  license: BSD-3-Clause
  license_file: src/wslink/LICENSE

extra:
  recipe-maintainers:
    - banesullivan
    - jourdain
    - kwrobot
