{% set name = "wslink" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wslink-{{ version }}.tar.gz
  sha256: a05ab62aa592bcf63053b0164004e5f91e10ab01acf231b22a6a424162a7be19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp <4

test:
  imports:
    - wslink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kitware/wslink
  summary: Python/JavaScript library for communicating over WebSocket
  license: BSD-3-Clause
  license_file: src/wslink/LICENSE

extra:
  recipe-maintainers:
    - banesullivan
    - jourdain
    - kwrobot
