{% set name = "wslink" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wslink-{{ version }}.tar.gz
  sha256: 697c2f3d0bd03c48be4c084766fbfe55f0e0308707a3fbc6336b0680f5ae0dcc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp <4
    - msgpack-python >=1,<2

test:
  imports:
    - wslink
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kitware/wslink
  summary: Python/JavaScript library for communicating over WebSocket
  license: BSD-3-Clause
  license_file: src/wslink/LICENSE

extra:
  recipe-maintainers:
    - banesullivan
    - jourdain
    - kwrobot
