{% set name = "wslink" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wslink-{{ version }}.tar.gz
  sha256: 4e1b181f6adf1b52bf27ac531493bdac06ef1ce0277d7b09fbbd24f33a228be9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aiohttp <4
    - msgpack >=1,<2

test:
  imports:
    - wslink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kitware/wslink
  summary: Python/JavaScript library for communicating over WebSocket
  license: BSD-3-Clause
  license_file: src/wslink/LICENSE

extra:
  recipe-maintainers:
    - banesullivan
    - jourdain
    - kwrobot
